{
    "name": "Mercas Base",
    "version": "19.0.1.0.0",
    "summary": "Módulo base para gestión de mercados mayoristas de frutas",
    "author": "Antonio Cánovas",
    "license": "LGPL-3",
    "category": "Inventory",
    "depends": [
        "purchase",
        "stock",
        "account",
        "sale_stock",
        "contacts",
        "purchase_lot",
        "sale_order_lot_selection",
        "bus",
        "product",
    ],
    "data": [
        "security/mercas_security.xml",
        "security/ir.model.access.csv",
        "views/res_company_views.xml",
        "views/res_partner_views.xml",
        "views/res_country_views.xml",
        "views/account_move_views.xml",
        "wizard/stock_lot_invoice_wizard_views.xml",
        "wizard/stock_lot_change_wizard_views.xml",
        "wizard/mercas_label_print_wizard_views.xml",
        "views/stock_lot_views.xml",
        "views/purchase_order_views.xml",
        "views/product_template_views.xml",
        "views/sale_order_views.xml",
        "views/mercas_menu.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "mercas_base/static/src/js/sale_order_lines_bus_notification.js",
            "mercas_base/static/src/js/product_qty_datetime_icon.js",
            "mercas_base/static/src/xml/product_qty_datetime_icon.xml",
        ],
    },
    "post_init_hook": "post_init_hook",
    "installable": True,
    "auto_install": False,
}
